mod db;
mod pricing;
mod scan;

use clap::Parser;
use rayon::prelude::*;
use std::path::PathBuf;
use walkdir::WalkDir;

#[derive(Parser)]
#[command(name = "amplifier-cost-scan", about = "Amplifier session cost scanner")]
struct Cli {
    /// Amplifier home directory (default: ~/.amplifier)
    #[arg(long)]
    home: Option<String>,

    /// SQLite summary database path
    #[arg(long)]
    db: Option<String>,

    /// Pricing JSON file (generated by the Python side)
    #[arg(long)]
    pricing: Option<String>,

    /// Re-scan every N seconds; 0 = run once and exit
    #[arg(long, default_value = "0")]
    watch: u64,

    /// Rayon thread-pool size; 0 = auto (one thread per logical CPU)
    #[arg(long, default_value = "0")]
    workers: usize,
}

fn main() {
    let cli = Cli::parse();

    // Resolve paths
    let home = resolve_home(cli.home.as_deref().unwrap_or("~/.amplifier"));
    let db_path = cli
        .db
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join("cost-viewer").join("summaries.db"));
    let pricing_path = cli
        .pricing
        .map(PathBuf::from)
        .unwrap_or_else(|| home.join("cost-viewer").join("pricing.json"));

    // Override rayon thread count if requested
    if cli.workers > 0 {
        rayon::ThreadPoolBuilder::new()
            .num_threads(cli.workers)
            .build_global()
            .ok();
    }

    let pricing = pricing::PricingTable::load(&pricing_path);
    let mut conn = db::open(&db_path).expect("cannot open/create summaries.db");

    loop {
        match run_once(&home, &pricing, &mut conn) {
            Ok(n) => eprintln!("[scanner] scan complete — {n} sessions updated"),
            Err(e) => eprintln!("[scanner] scan error: {e}"),
        }
        if cli.watch == 0 {
            break;
        }
        std::thread::sleep(std::time::Duration::from_secs(cli.watch));
    }
}

/// One full scan pass.
fn run_once(
    home: &PathBuf,
    pricing: &pricing::PricingTable,
    conn: &mut rusqlite::Connection,
) -> rusqlite::Result<usize> {
    // Walk all events.jsonl files (depth 4 = projects/<slug>/sessions/<id>/events.jsonl)
    let files: Vec<(String, PathBuf)> = WalkDir::new(home.join("projects"))
        .min_depth(4)
        .max_depth(4)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_name() == "events.jsonl")
        .filter_map(|e| {
            let sid = e.path().parent()?.file_name()?.to_str()?.to_string();
            Some((sid, e.into_path()))
        })
        .collect();

    // Load all existing states in one query — avoids N+1 DB round-trips
    let states = db::load_states(conn)?;

    // Parallel scan: rayon work-steals across CPU cores
    let results: Vec<scan::ScanResult> = files
        .par_iter()
        .filter_map(|(sid, path)| {
            let (last_offset, is_complete) =
                states.get(sid.as_str()).copied().unwrap_or((0, false));
            if is_complete {
                return None; // frozen — skip forever
            }
            scan::scan_file(sid, path, last_offset, pricing)
        })
        .collect();

    let n = results.len();
    db::upsert_batch(conn, &results)?;
    Ok(n)
}

// ── helpers ───────────────────────────────────────────────────────────────────

fn resolve_home(path: &str) -> PathBuf {
    if let Some(rest) = path.strip_prefix("~/") {
        if let Ok(home) = std::env::var("HOME") {
            return PathBuf::from(home).join(rest);
        }
    }
    PathBuf::from(path)
}
